# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 14:56
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20170729_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(
                choices=[(1, 'Male'), (2, 'Female'), (3, 'Others')], max_length=10),
        ),
    ]
