# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 12:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_remove_admin_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='created_by',
        ),
    ]
