# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 19:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='bank_account_no',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='bank_branch_name',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='bank_name',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='ifsc_code',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='joint_application',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='registration',
            name='registration_id',
            field=models.CharField(default='asd', max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='flat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='registrations', to='schemes.Flat'),
        ),
    ]
