# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 17:27
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_registration', '0013_auto_20170728_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('datafile', models.FileField(upload_to='')),
                ('owner', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='user_registration.User')),
            ],
        ),
    ]
