# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 06:20
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document',
            field=models.TextField(),
        ),
    ]
