# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 19:57
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_auto_20170728_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                    related_name='documents', to='user_registration.User'),
        ),
    ]
