# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 10:06
from __future__ import unicode_literals

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0004_auto_20170724_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_logout', models.BooleanField(default=None)),
                ('logout_at', models.DateTimeField(default=None)),
                ('session_id', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='user_registration.User')),
            ],
        ),
        migrations.RemoveField(
            model_name='loginlog',
            name='user',
        ),
        migrations.DeleteModel(
            name='LoginLog',
        ),
    ]
