# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 10:18
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0006_auto_20170725_1007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='auto_logout',
            field=models.NullBooleanField(default=None),
        ),
    ]
