# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 10:19
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0007_auto_20170725_1018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='logout_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
