# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 03:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0009_auto_20170725_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(
                message='Phone number not valid.', regex='^(?:\\+?91)?[789]\\d{9,10}$')]),
        ),
    ]
