# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 05:03
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0011_auto_20170726_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator(
                message='phone number not valid', regex='^(?:\\+?91)?[789]\\d{9,10}$')]),
        ),
    ]
