# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-28 19:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('user_registration', '0012_auto_20170726_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='aadhar_no',
            field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator(
                message='Aadhar number not valid.', regex='^[0-9]{12}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='pan_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(
                message='Pan number not valid.', regex='^[A-Z]{5}[0-9]{4}[A-Z]{1}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, unique=True, validators=[django.core.validators.RegexValidator(
                message='Phone number not valid.', regex='^(?:\\+?91)?[789]\\d{9,10}$')]),
        ),
    ]
