# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 02:08
from __future__ import unicode_literals

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpet_area', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('accomodation', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('estimate_cost', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('application_amount', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('maintenance_deposit', models.BigIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('no_of_flats', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlatType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name')),
                ('location', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('draw_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='flat_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schemes.FlatType'),
        ),
        migrations.AddField(
            model_name='flat',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='schemes.Scheme'),
        ),
    ]
