# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-30 06:44
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheme',
            name='details',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
