# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 07:57
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flattype',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from='name'),
        ),
        migrations.AlterField(
            model_name='scheme',
            name='slug',
            field=autoslug.fields.AutoSlugField(
                editable=False, populate_from='name'),
        ),
    ]
