# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 12:11
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0002_auto_20170726_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='accomodation',
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='application_amount',
            field=models.BigIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='carpet_area',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[
                                      django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='estimate_cost',
            field=models.BigIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='flat',
            name='maintenance_deposit',
            field=models.BigIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
