# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-26 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schemes', '0003_auto_20170726_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flat',
            name='scheme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flats', to='schemes.Scheme'),
        ),
    ]
