# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-25 04:21
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='notifications',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(max_length=500)),
                ('validity', models.CharField(max_length=50)),
            ],
        ),
    ]
