# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 09:45
from __future__ import unicode_literals

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0003_auto_20170726_0426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='scheme',
            new_name='message',
        ),
        migrations.AddField(
            model_name='notification',
            name='url',
            field=models.URLField(default=None, null=True),
        ),
    ]
